name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Change this to your main branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

    - name: Copy files to Azure VM
      run: |
        scp -o StrictHostKeyChecking=no -r ./* azureuser@20.193.147.227:/demo/
